server:
  port: 8085

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: pet-service
          uri: lb://pet-service
          predicates:
            - Path=/pets/**
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/appointments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
