server:
  port: 8080

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/petcare
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
